name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

    - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

    - name: Install
        run: pnpm install --frozen-lockfile

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: AkiyamaMinami/akiyamaminami.github.io
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: pnpm && pnpm docs:build
        BUILD_DIR: docs/.vuepress/dist
        CNAME: https://mobs.fun