name: Deploy Blog

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - name: Set pnpm
        run: pnpm config set auto-install-peers true
      - name: Install
        run: pnpm install -frozen-lockfile

      - name: Build
        run: pnpm docs:build

      - name: 📚 Deploy Docs to GitHub Pages 📚
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          cname: mobs.fun
          publish_dir: docs/.vuepress/dist
          publish_branch: gh-page